### ISSUE TITLE
extract-qt-installer hang on travis

### ISSUE THREAD

**Issue by tsteven4** [benlau/qtci#15]
Something between 64815b69f0eeb11e7d5bed87b1cb50beb90da604 (5/21/2018) and 4991cf60edfddcde8ffecd073ba25e3529bba451 (9/15/2018) in extract_qt_installer causes a hang on travis with Qt 5.9.7.

Here is a log with 4991cf60:
 https://travis-ci.org/tsteven4/gpsbabel/jobs/450037144
This failure repeated a couple of times.

and here is a log with 64815b69:
https://travis-ci.org/tsteven4/gpsbabel/jobs/450043922

**Comment by tsteven4** [comment]
This problem first appeared in 044d4fe753a84be20f0cfc7d3ef9beb39d638542

Here is a log with 044d4fe7:
https://travis-ci.org/tsteven4/qtci/builds/450067060

and here is one with 2b25dc70ff3bc70cd549076b99ebd8b15a2e5a66
https://travis-ci.org/tsteven4/qtci/builds/450066124

The only things these branches have changes is .travis.yml and permissions on install_qt.

**Comment by tsteven4** [comment]
#13 appears to fix this issue.  note I am testing with qt 5.9.7, so perhaps #13 can claim a fix for 5.9.7, 5.10 and 5.11.

https://travis-ci.org/tsteven4/qtci/builds/450078446

**Comment by tsteven4** [comment]
I modified .travis.yml to run a more complete regression on install-qt here
https://github.com/benlau/qtci/compare/master...tsteven4:travis_matrix?expand=1

This https://travis-ci.org/tsteven4/qtci/builds/450089062 shows we don't hang with installers from
5.9.0, 5.91, 5.9.2, 5.9.3, 5.10.0
but we do hang with
5.9.4, 5.9.5, 5.9.6, 5.9.7, 5.10.1, 5.11.0, 5.11.1, 5.11.2

It would be nice to lower the timeout on travis so the failures didn't take so long.

I could submit this as a PR so we could improve regression coverage.

**Comment by benlau** [comment]
hi @tsteven4 ,

Sorry for late reply. Your .travis.yml looks good for me. (but Travis will cry). Please feel free to submit a PR to me. thx.

**Comment by bjorn** [comment]
If #16 proved that this issue was solved (most likely by #13), maybe it's time to close this issue? :-)
