### ISSUE TITLE
welcome page freeze

### ISSUE THREAD

**Issue by tsteven4** [benlau/qtci#6]
I have experienced the welcome page freeze with Qt 5.9.5 on mac os x, despite #4 which included 85cb986b66af4807a928c70e13d82d00dc26ebf0
It is intermittent.
There are some reports of success using longer delays, e.g. https://forum.qt.io/topic/85705/qt-linux-online-installer-3-0-2-my-unattended-script-broken/2
Somewhere I also found an example using a 10s delay.

**Comment by benlau** [comment]
I have another solution which doesn't need a timeout value. Could you try it?

64815b69f0eeb11e7d5bed87b1cb50beb90da604
